spring:
  profiles:
    active: dev
  application:
    name: wx
  resources:
    static-locations: classpath:/static/
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 20MB
  cache:
    #使用默认的ConcurrentMap
    type: simple
    cache-names: paramCache,defaultCache
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_wx?useSSL=false&serverTimezone=GMT%2B8
    password: root
    username: root

# 配置log
logging:
  level:
    root: warn
    # 配置日志关注点，关注 mapper包下 最低级别日志
    me.zqt.wx: trace
  # 日志输出格式
  pattern:
    # 级别 内容 换行
    console: '%p%m%n'

# 配置mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      # 配置通用表前缀。如tb_user 表，User实体类无需使用@TableName("tb_user")
      table-prefix: tb_
  # mapper.xml 存储路径
  mapper-locations: classpath:/mappers/*.xml

#server:
#  tomcat:
#    uri-encoding: UTF-8